USE [v0071053_transportare_gps]
GO
/****** Object:  ForeignKey [FK_ALUMNO_ESCUELA]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_ESCUELA]
GO
/****** Object:  ForeignKey [FK_ALUMNO_INFORMACION_ALUMNO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_INFORMACION_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_INFORMACION_ALUMNO]
GO
/****** Object:  ForeignKey [FK_ALUMNO_INFORMACION_NOTIFICACION]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_INFORMACION_NOTIFICACION]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_INFORMACION_NOTIFICACION]
GO
/****** Object:  ForeignKey [FK_ALUMNO_RESPONSABLE_ALUMNO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_RESPONSABLE_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_RESPONSABLE_ALUMNO]
GO
/****** Object:  ForeignKey [FK_ALUMNO_TRANSPORTE]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_TRANSPORTE]
GO
/****** Object:  ForeignKey [FK_ALUMNO_X_USUARIO_ALUMNO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_X_USUARIO_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO_X_USUARIO]'))
ALTER TABLE [dbo].[ALUMNO_X_USUARIO] DROP CONSTRAINT [FK_ALUMNO_X_USUARIO_ALUMNO]
GO
/****** Object:  ForeignKey [FK_ALUMNO_X_USUARIO_USUARIO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_X_USUARIO_USUARIO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO_X_USUARIO]'))
ALTER TABLE [dbo].[ALUMNO_X_USUARIO] DROP CONSTRAINT [FK_ALUMNO_X_USUARIO_USUARIO]
GO
/****** Object:  ForeignKey [FK_BITACORA_EVENTO_ALUMNO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO] DROP CONSTRAINT [FK_BITACORA_EVENTO_ALUMNO]
GO
/****** Object:  ForeignKey [FK_BITACORA_EVENTO_DETALLE_EVENTO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_DETALLE_EVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO] DROP CONSTRAINT [FK_BITACORA_EVENTO_DETALLE_EVENTO]
GO
/****** Object:  ForeignKey [FK_BITACORA_EVENTO_TRANSPORTE]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO] DROP CONSTRAINT [FK_BITACORA_EVENTO_TRANSPORTE]
GO
/****** Object:  ForeignKey [FK_CHOFER_INFORMACION_CONTACTO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CHOFER_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CHOFER]'))
ALTER TABLE [dbo].[CHOFER] DROP CONSTRAINT [FK_CHOFER_INFORMACION_CONTACTO]
GO
/****** Object:  ForeignKey [FK_DETALLE_EVENTO_TIPO_EVENTO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DETALLE_EVENTO_TIPO_EVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[DETALLE_EVENTO]'))
ALTER TABLE [dbo].[DETALLE_EVENTO] DROP CONSTRAINT [FK_DETALLE_EVENTO_TIPO_EVENTO]
GO
/****** Object:  ForeignKey [FK_ESCUELA_ESCUELA_X_ADMINISTRADOR]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ESCUELA_ESCUELA_X_ADMINISTRADOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[ESCUELA]'))
ALTER TABLE [dbo].[ESCUELA] DROP CONSTRAINT [FK_ESCUELA_ESCUELA_X_ADMINISTRADOR]
GO
/****** Object:  ForeignKey [FK_ESCUELA_X_ADMINISTRADOR_ADMINISTRADOR]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ESCUELA_X_ADMINISTRADOR_ADMINISTRADOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[ESCUELA_X_ADMINISTRADOR]'))
ALTER TABLE [dbo].[ESCUELA_X_ADMINISTRADOR] DROP CONSTRAINT [FK_ESCUELA_X_ADMINISTRADOR_ADMINISTRADOR]
GO
/****** Object:  ForeignKey [FK_GPS_LOCATION_TRANSPORTE]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_GPS_LOCATION_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[GPS_LOCATION]'))
ALTER TABLE [dbo].[GPS_LOCATION] DROP CONSTRAINT [FK_GPS_LOCATION_TRANSPORTE]
GO
/****** Object:  ForeignKey [FK_RESPONSABLE_ALUMNO_INFORMACION_CONTACTO]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RESPONSABLE_ALUMNO_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[RESPONSABLE_ALUMNO]'))
ALTER TABLE [dbo].[RESPONSABLE_ALUMNO] DROP CONSTRAINT [FK_RESPONSABLE_ALUMNO_INFORMACION_CONTACTO]
GO
/****** Object:  ForeignKey [FK_TRANSPORTE_CHOFER]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_CHOFER]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE] DROP CONSTRAINT [FK_TRANSPORTE_CHOFER]
GO
/****** Object:  ForeignKey [FK_TRANSPORTE_ESCUELA]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE] DROP CONSTRAINT [FK_TRANSPORTE_ESCUELA]
GO
/****** Object:  ForeignKey [FK_TRANSPORTE_INFORMACION_UNIDAD]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_INFORMACION_UNIDAD]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE] DROP CONSTRAINT [FK_TRANSPORTE_INFORMACION_UNIDAD]
GO
/****** Object:  ForeignKey [FK_USUARIO_INFORMACION_CONTACTO]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO]'))
ALTER TABLE [dbo].[USUARIO] DROP CONSTRAINT [FK_USUARIO_INFORMACION_CONTACTO]
GO
/****** Object:  ForeignKey [FK_USUARIO_X_ESCUELA_ESCUELA]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_X_ESCUELA_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO_X_ESCUELA]'))
ALTER TABLE [dbo].[USUARIO_X_ESCUELA] DROP CONSTRAINT [FK_USUARIO_X_ESCUELA_ESCUELA]
GO
/****** Object:  ForeignKey [FK_USUARIO_X_ESCUELA_USUARIO]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_X_ESCUELA_USUARIO]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO_X_ESCUELA]'))
ALTER TABLE [dbo].[USUARIO_X_ESCUELA] DROP CONSTRAINT [FK_USUARIO_X_ESCUELA_USUARIO]
GO
/****** Object:  Table [dbo].[ALUMNO_X_USUARIO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_X_USUARIO_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO_X_USUARIO]'))
ALTER TABLE [dbo].[ALUMNO_X_USUARIO] DROP CONSTRAINT [FK_ALUMNO_X_USUARIO_ALUMNO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_X_USUARIO_USUARIO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO_X_USUARIO]'))
ALTER TABLE [dbo].[ALUMNO_X_USUARIO] DROP CONSTRAINT [FK_ALUMNO_X_USUARIO_USUARIO]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ALUMNO_X_USUARIO]') AND type in (N'U'))
DROP TABLE [dbo].[ALUMNO_X_USUARIO]
GO
/****** Object:  Table [dbo].[BITACORA_EVENTO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO] DROP CONSTRAINT [FK_BITACORA_EVENTO_ALUMNO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_DETALLE_EVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO] DROP CONSTRAINT [FK_BITACORA_EVENTO_DETALLE_EVENTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO] DROP CONSTRAINT [FK_BITACORA_EVENTO_TRANSPORTE]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]') AND type in (N'U'))
DROP TABLE [dbo].[BITACORA_EVENTO]
GO
/****** Object:  Table [dbo].[ALUMNO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_ESCUELA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_INFORMACION_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_INFORMACION_ALUMNO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_INFORMACION_NOTIFICACION]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_INFORMACION_NOTIFICACION]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_RESPONSABLE_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_RESPONSABLE_ALUMNO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] DROP CONSTRAINT [FK_ALUMNO_TRANSPORTE]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ALUMNO]') AND type in (N'U'))
DROP TABLE [dbo].[ALUMNO]
GO
/****** Object:  Table [dbo].[GPS_LOCATION]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_GPS_LOCATION_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[GPS_LOCATION]'))
ALTER TABLE [dbo].[GPS_LOCATION] DROP CONSTRAINT [FK_GPS_LOCATION_TRANSPORTE]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GPS_LOCATION]') AND type in (N'U'))
DROP TABLE [dbo].[GPS_LOCATION]
GO
/****** Object:  Table [dbo].[TRANSPORTE]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_CHOFER]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE] DROP CONSTRAINT [FK_TRANSPORTE_CHOFER]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE] DROP CONSTRAINT [FK_TRANSPORTE_ESCUELA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_INFORMACION_UNIDAD]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE] DROP CONSTRAINT [FK_TRANSPORTE_INFORMACION_UNIDAD]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]') AND type in (N'U'))
DROP TABLE [dbo].[TRANSPORTE]
GO
/****** Object:  Table [dbo].[USUARIO_X_ESCUELA]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_X_ESCUELA_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO_X_ESCUELA]'))
ALTER TABLE [dbo].[USUARIO_X_ESCUELA] DROP CONSTRAINT [FK_USUARIO_X_ESCUELA_ESCUELA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_X_ESCUELA_USUARIO]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO_X_ESCUELA]'))
ALTER TABLE [dbo].[USUARIO_X_ESCUELA] DROP CONSTRAINT [FK_USUARIO_X_ESCUELA_USUARIO]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIO_X_ESCUELA]') AND type in (N'U'))
DROP TABLE [dbo].[USUARIO_X_ESCUELA]
GO
/****** Object:  Table [dbo].[ESCUELA]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ESCUELA_ESCUELA_X_ADMINISTRADOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[ESCUELA]'))
ALTER TABLE [dbo].[ESCUELA] DROP CONSTRAINT [FK_ESCUELA_ESCUELA_X_ADMINISTRADOR]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESCUELA]') AND type in (N'U'))
DROP TABLE [dbo].[ESCUELA]
GO
/****** Object:  Table [dbo].[ESCUELA_X_ADMINISTRADOR]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ESCUELA_X_ADMINISTRADOR_ADMINISTRADOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[ESCUELA_X_ADMINISTRADOR]'))
ALTER TABLE [dbo].[ESCUELA_X_ADMINISTRADOR] DROP CONSTRAINT [FK_ESCUELA_X_ADMINISTRADOR_ADMINISTRADOR]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESCUELA_X_ADMINISTRADOR]') AND type in (N'U'))
DROP TABLE [dbo].[ESCUELA_X_ADMINISTRADOR]
GO
/****** Object:  Table [dbo].[RESPONSABLE_ALUMNO]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RESPONSABLE_ALUMNO_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[RESPONSABLE_ALUMNO]'))
ALTER TABLE [dbo].[RESPONSABLE_ALUMNO] DROP CONSTRAINT [FK_RESPONSABLE_ALUMNO_INFORMACION_CONTACTO]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RESPONSABLE_ALUMNO]') AND type in (N'U'))
DROP TABLE [dbo].[RESPONSABLE_ALUMNO]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO]'))
ALTER TABLE [dbo].[USUARIO] DROP CONSTRAINT [FK_USUARIO_INFORMACION_CONTACTO]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIO]') AND type in (N'U'))
DROP TABLE [dbo].[USUARIO]
GO
/****** Object:  Table [dbo].[CHOFER]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CHOFER_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CHOFER]'))
ALTER TABLE [dbo].[CHOFER] DROP CONSTRAINT [FK_CHOFER_INFORMACION_CONTACTO]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CHOFER]') AND type in (N'U'))
DROP TABLE [dbo].[CHOFER]
GO
/****** Object:  Table [dbo].[DETALLE_EVENTO]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DETALLE_EVENTO_TIPO_EVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[DETALLE_EVENTO]'))
ALTER TABLE [dbo].[DETALLE_EVENTO] DROP CONSTRAINT [FK_DETALLE_EVENTO_TIPO_EVENTO]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DETALLE_EVENTO]') AND type in (N'U'))
DROP TABLE [dbo].[DETALLE_EVENTO]
GO
/****** Object:  Table [dbo].[ADMINISTRADOR]    Script Date: 07/20/2015 16:52:06 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ADMINISTRADOR]') AND type in (N'U'))
DROP TABLE [dbo].[ADMINISTRADOR]
GO
/****** Object:  Table [dbo].[INFORMACION_ALUMNO]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INFORMACION_ALUMNO]') AND type in (N'U'))
DROP TABLE [dbo].[INFORMACION_ALUMNO]
GO
/****** Object:  Table [dbo].[INFORMACION_CONTACTO]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INFORMACION_CONTACTO]') AND type in (N'U'))
DROP TABLE [dbo].[INFORMACION_CONTACTO]
GO
/****** Object:  Table [dbo].[INFORMACION_NOTIFICACION]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INFORMACION_NOTIFICACION]') AND type in (N'U'))
DROP TABLE [dbo].[INFORMACION_NOTIFICACION]
GO
/****** Object:  Table [dbo].[INFORMACION_UNIDAD]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INFORMACION_UNIDAD]') AND type in (N'U'))
DROP TABLE [dbo].[INFORMACION_UNIDAD]
GO
/****** Object:  Table [dbo].[TIPO_EVENTO]    Script Date: 07/20/2015 16:52:07 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPO_EVENTO]') AND type in (N'U'))
DROP TABLE [dbo].[TIPO_EVENTO]
GO
/****** Object:  Table [dbo].[TIPO_EVENTO]    Script Date: 07/20/2015 16:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPO_EVENTO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TIPO_EVENTO](
	[ID_TIPO_EVENTO] [int] NOT NULL,
	[NOMBRE_EVENTO] [int] NOT NULL,
 CONSTRAINT [PK_TIPO_EVENTO] PRIMARY KEY CLUSTERED 
(
	[ID_TIPO_EVENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[INFORMACION_UNIDAD]    Script Date: 07/20/2015 16:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INFORMACION_UNIDAD]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[INFORMACION_UNIDAD](
	[ID_INFORMACION_UNIDAD] [int] NOT NULL,
	[MODELO] [int] NOT NULL,
	[VERSION] [varchar](150) NULL,
	[MARCA] [varchar](50) NOT NULL,
	[SUBMARCA] [varchar](50) NOT NULL,
	[PLACAS] [varchar](50) NOT NULL,
	[CAPACIDAD] [int] NOT NULL,
	[ID_PROPIETARIO_UNIDAD] [nchar](10) NULL,
	[ID_RESPONSABLE_UNIDAD] [nchar](10) NULL,
	[ID_ASEGURADORA] [int] NULL,
	[NUMERO_POLIZA_SEGURO] [nchar](10) NULL,
 CONSTRAINT [PK_DATOS_UNIDAD] PRIMARY KEY CLUSTERED 
(
	[ID_INFORMACION_UNIDAD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[INFORMACION_NOTIFICACION]    Script Date: 07/20/2015 16:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INFORMACION_NOTIFICACION]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[INFORMACION_NOTIFICACION](
	[ID_INFORMACION_NOTIFICACION] [int] NOT NULL,
 CONSTRAINT [PK_INFORMACION_NOTIFICACION] PRIMARY KEY CLUSTERED 
(
	[ID_INFORMACION_NOTIFICACION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[INFORMACION_CONTACTO]    Script Date: 07/20/2015 16:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INFORMACION_CONTACTO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[INFORMACION_CONTACTO](
	[ID_INFORMACION_CONTACTO] [int] NOT NULL,
	[NOMBRE] [nchar](10) NOT NULL,
	[APELLIDO_PATERNO] [nchar](10) NOT NULL,
	[APELLIDO_MATERNO] [nchar](10) NULL,
	[FECHA_NACIMIENTO] [nchar](10) NULL,
	[SEXO] [nchar](10) NULL,
	[CALLE_DIRECCION] [nchar](10) NULL,
	[NUMERO_INTERIOR_DIRECCION] [nchar](10) NULL,
	[NUMERO_EXTERIOR_DIRECCION] [nchar](10) NULL,
	[CP] [nchar](10) NULL,
	[COLONIA_DIRECCION] [nchar](10) NULL,
	[CORREO_ELECTRONICO] [nchar](10) NULL,
	[TELEFONO_OFICINA] [nchar](10) NULL,
	[TELEFONO_CASA] [nchar](10) NULL,
	[CELULAR] [nchar](10) NULL,
 CONSTRAINT [PK_DATOS_CONTACTO] PRIMARY KEY CLUSTERED 
(
	[ID_INFORMACION_CONTACTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[INFORMACION_ALUMNO]    Script Date: 07/20/2015 16:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INFORMACION_ALUMNO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[INFORMACION_ALUMNO](
	[ID_INFORMACION_ALUMNO] [int] NOT NULL,
	[NOMBRE] [nchar](10) NULL,
	[APELLIDO_PATERNO] [nchar](10) NULL,
	[APELLIDO_MATERNO] [nchar](10) NULL,
	[SEXO] [nchar](10) NULL,
	[EDAD] [nchar](10) NULL,
	[CALLE_DIRECCION] [nchar](10) NULL,
	[NUMERO_INTERIOR_DIRECCION] [nchar](10) NULL,
	[NUMERO_EXTERIOR_DIREECION] [nchar](10) NULL,
	[CP] [nchar](10) NULL,
	[COLONIA_DIRECCION] [nchar](10) NULL,
 CONSTRAINT [PK_INFORMACION_ALUMNO] PRIMARY KEY CLUSTERED 
(
	[ID_INFORMACION_ALUMNO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[ADMINISTRADOR]    Script Date: 07/20/2015 16:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ADMINISTRADOR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ADMINISTRADOR](
	[ID_ADMINISTRADOR] [int] NOT NULL,
	[IS_SUPER] [bit] NULL,
	[USUARIO] [nchar](10) NULL,
	[PASSWORD] [nchar](10) NULL,
 CONSTRAINT [PK_ADMINISTRADOR] PRIMARY KEY CLUSTERED 
(
	[ID_ADMINISTRADOR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[DETALLE_EVENTO]    Script Date: 07/20/2015 16:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DETALLE_EVENTO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DETALLE_EVENTO](
	[ID_DETALLE_EVENTO] [int] NOT NULL,
	[ID_TIPO_EVENTO] [int] NULL,
	[LATITUDE] [decimal](10, 7) NULL,
	[LOGITUD] [decimal](10, 7) NULL,
	[DESCRIPCION_EVENTO] [nchar](10) NULL,
 CONSTRAINT [PK_DETALLE_EVENTO] PRIMARY KEY CLUSTERED 
(
	[ID_DETALLE_EVENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[CHOFER]    Script Date: 07/20/2015 16:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CHOFER]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CHOFER](
	[ID_CHOFER] [int] NOT NULL,
	[ID_INFORMACION_CONTACTO] [int] NOT NULL,
	[NUMERO_LICENCIA] [varchar](20) NULL,
 CONSTRAINT [PK_CHOFER] PRIMARY KEY CLUSTERED 
(
	[ID_CHOFER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 07/20/2015 16:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[USUARIO](
	[ID_USUARIO] [int] NOT NULL,
	[ID_INFORMACION_CONTACTO] [int] NOT NULL,
	[USUARIO] [varchar](20) NOT NULL,
	[PASSWORD] [varchar](20) NOT NULL,
	[FECHA_ALTA] [date] NULL,
	[FECHA_ACTUALIZACION] [date] NOT NULL,
	[ID_ADMINISTRADOR_ALTA] [int] NULL,
	[ID_ADMINISTRADOR_ACTUALIZACION] [int] NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[RESPONSABLE_ALUMNO]    Script Date: 07/20/2015 16:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RESPONSABLE_ALUMNO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[RESPONSABLE_ALUMNO](
	[ID_RESPONSABLE_ALUMNO] [int] NOT NULL,
	[ID_INFORMACION_CONTACTO] [int] NOT NULL,
 CONSTRAINT [PK_RESPONSABLE_ALUMNO] PRIMARY KEY CLUSTERED 
(
	[ID_RESPONSABLE_ALUMNO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[ESCUELA_X_ADMINISTRADOR]    Script Date: 07/20/2015 16:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESCUELA_X_ADMINISTRADOR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ESCUELA_X_ADMINISTRADOR](
	[ID_ESCUELA_X_ADMINISTRADOR] [int] NOT NULL,
	[ID_ESCUELA] [int] NOT NULL,
	[ID_ADMINISTRADOR] [int] NOT NULL,
 CONSTRAINT [PK_ESCUELA_X_ADMINISTRADOR] PRIMARY KEY CLUSTERED 
(
	[ID_ESCUELA_X_ADMINISTRADOR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[ESCUELA]    Script Date: 07/20/2015 16:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESCUELA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ESCUELA](
	[ID_ESCUELA] [int] NOT NULL,
	[NOMBRE_ESCUELA] [varchar](150) NOT NULL,
	[ID_CONTACTO_ESCUELA] [int] NOT NULL,
	[ACTIVA] [bit] NOT NULL,
	[ID_USUARIO_ALTA] [int] NOT NULL,
	[ID_USUARIO_ACTUALIZACION] [int] NULL,
	[FECHA_ALTA] [date] NOT NULL,
	[FECHA_ACTUALIZACION] [date] NULL,
 CONSTRAINT [PK_ESCUELA] PRIMARY KEY CLUSTERED 
(
	[ID_ESCUELA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USUARIO_X_ESCUELA]    Script Date: 07/20/2015 16:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIO_X_ESCUELA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[USUARIO_X_ESCUELA](
	[ID_USUARIO_X_ESCUELA] [int] NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[ID_ESCUELA] [int] NOT NULL,
 CONSTRAINT [PK_USUARIO_X_ESCUELA] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO_X_ESCUELA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[TRANSPORTE]    Script Date: 07/20/2015 16:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TRANSPORTE](
	[ID_TRANSPORTE] [int] NOT NULL,
	[NOMBRE_TRANPORTE] [varchar](50) NOT NULL,
	[DESCRIPCION_TRANSPORTE] [varchar](250) NULL,
	[ID_ESCUELA] [int] NOT NULL,
	[ID_CHOFER] [int] NOT NULL,
	[FECHA_ALTA] [date] NOT NULL,
	[FECHA_ACTUALIZACION] [date] NULL,
	[ID_USUARIO_ALTA] [int] NOT NULL,
	[ID_USUARIO_ACTUALIZACION] [int] NULL,
	[ACTIVO] [bit] NOT NULL,
	[PROPIO] [bit] NOT NULL,
	[ID_INFORMACION_UNIDAD] [int] NOT NULL,
 CONSTRAINT [PK_TRANSPORTE] PRIMARY KEY CLUSTERED 
(
	[ID_TRANSPORTE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GPS_LOCATION]    Script Date: 07/20/2015 16:52:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GPS_LOCATION]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[GPS_LOCATION](
	[ID_GPS_LOCATION] [int] NOT NULL,
	[LAST_UPDATE] [datetime] NOT NULL,
	[LATITUDE] [decimal](10, 7) NOT NULL,
	[LONGITUDE] [decimal](10, 7) NOT NULL,
	[SESSION_ID] [varchar](50) NOT NULL,
	[SPEED] [int] NOT NULL,
	[DIRECTION] [int] NOT NULL,
	[DISTANCE] [decimal](10, 1) NOT NULL,
	[GPS_TIME] [datetime] NOT NULL,
	[LOCATION_METHOD] [varchar](50) NOT NULL,
	[ACCURACY] [int] NOT NULL,
	[EXTRA_INFO] [varchar](255) NOT NULL,
	[EVENT_TYPE] [varchar](50) NOT NULL,
	[ID_TRANSPORTE] [int] NULL,
 CONSTRAINT [PK_GPS_LOCATION] PRIMARY KEY CLUSTERED 
(
	[ID_GPS_LOCATION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 1) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[GPS_LOCATION] ([ID_GPS_LOCATION], [LAST_UPDATE], [LATITUDE], [LONGITUDE], [SESSION_ID], [SPEED], [DIRECTION], [DISTANCE], [GPS_TIME], [LOCATION_METHOD], [ACCURACY], [EXTRA_INFO], [EVENT_TYPE], [ID_TRANSPORTE]) VALUES (1, CAST(0x000098AB007D84D0 AS DateTime), CAST(47.6273270 AS Decimal(10, 7)), CAST(-122.3256910 AS Decimal(10, 7)), N'8BA21D90-3F90-407F-BAAE-800B04B1F5EB', 0, 0, CAST(0.0 AS Decimal(10, 1)), CAST(0x000098AB007D84D0 AS DateTime), N'na', 137, N'na', N'gpsTracker', NULL)
INSERT [dbo].[GPS_LOCATION] ([ID_GPS_LOCATION], [LAST_UPDATE], [LATITUDE], [LONGITUDE], [SESSION_ID], [SPEED], [DIRECTION], [DISTANCE], [GPS_TIME], [LOCATION_METHOD], [ACCURACY], [EXTRA_INFO], [EVENT_TYPE], [ID_TRANSPORTE]) VALUES (2, CAST(0x000098AB007DCB20 AS DateTime), CAST(47.6072580 AS Decimal(10, 7)), CAST(-122.3300770 AS Decimal(10, 7)), N'8BA21D90-3F90-407F-BAAE-800B04B1F5EB', 0, 0, CAST(0.0 AS Decimal(10, 1)), CAST(0x000098AB007DCB20 AS DateTime), N'na', 137, N'na', N'gpsTracker', NULL)
INSERT [dbo].[GPS_LOCATION] ([ID_GPS_LOCATION], [LAST_UPDATE], [LATITUDE], [LONGITUDE], [SESSION_ID], [SPEED], [DIRECTION], [DISTANCE], [GPS_TIME], [LOCATION_METHOD], [ACCURACY], [EXTRA_INFO], [EVENT_TYPE], [ID_TRANSPORTE]) VALUES (3, CAST(0x000098AB007E1170 AS DateTime), CAST(47.6017030 AS Decimal(10, 7)), CAST(-122.3246700 AS Decimal(10, 7)), N'8BA21D90-3F90-407F-BAAE-800B04B1F5EB', 0, 0, CAST(0.0 AS Decimal(10, 1)), CAST(0x000098AB007E1170 AS DateTime), N'na', 137, N'na', N'gpsTracker', NULL)
INSERT [dbo].[GPS_LOCATION] ([ID_GPS_LOCATION], [LAST_UPDATE], [LATITUDE], [LONGITUDE], [SESSION_ID], [SPEED], [DIRECTION], [DISTANCE], [GPS_TIME], [LOCATION_METHOD], [ACCURACY], [EXTRA_INFO], [EVENT_TYPE], [ID_TRANSPORTE]) VALUES (4, CAST(0x000098AB007E57C0 AS DateTime), CAST(47.5937570 AS Decimal(10, 7)), CAST(-122.1950740 AS Decimal(10, 7)), N'8BA21D90-3F90-407F-BAAE-800B04B1F5EC', 0, 0, CAST(0.0 AS Decimal(10, 1)), CAST(0x000098AB007E57C0 AS DateTime), N'na', 137, N'na', N'gpsTracker', NULL)
INSERT [dbo].[GPS_LOCATION] ([ID_GPS_LOCATION], [LAST_UPDATE], [LATITUDE], [LONGITUDE], [SESSION_ID], [SPEED], [DIRECTION], [DISTANCE], [GPS_TIME], [LOCATION_METHOD], [ACCURACY], [EXTRA_INFO], [EVENT_TYPE], [ID_TRANSPORTE]) VALUES (5, CAST(0x000098AB007E9E10 AS DateTime), CAST(47.6013970 AS Decimal(10, 7)), CAST(-122.1903530 AS Decimal(10, 7)), N'8BA21D90-3F90-407F-BAAE-800B04B1F5EC', 0, 0, CAST(0.0 AS Decimal(10, 1)), CAST(0x000098AB007E9E10 AS DateTime), N'na', 137, N'na', N'gpsTracker', NULL)
INSERT [dbo].[GPS_LOCATION] ([ID_GPS_LOCATION], [LAST_UPDATE], [LATITUDE], [LONGITUDE], [SESSION_ID], [SPEED], [DIRECTION], [DISTANCE], [GPS_TIME], [LOCATION_METHOD], [ACCURACY], [EXTRA_INFO], [EVENT_TYPE], [ID_TRANSPORTE]) VALUES (6, CAST(0x000098AB007EE460 AS DateTime), CAST(47.6100200 AS Decimal(10, 7)), CAST(-122.1906970 AS Decimal(10, 7)), N'8BA21D90-3F90-407F-BAAE-800B04B1F5EC', 0, 0, CAST(0.0 AS Decimal(10, 1)), CAST(0x000098AB007EE460 AS DateTime), N'na', 137, N'na', N'gpsTracker', NULL)
INSERT [dbo].[GPS_LOCATION] ([ID_GPS_LOCATION], [LAST_UPDATE], [LATITUDE], [LONGITUDE], [SESSION_ID], [SPEED], [DIRECTION], [DISTANCE], [GPS_TIME], [LOCATION_METHOD], [ACCURACY], [EXTRA_INFO], [EVENT_TYPE], [ID_TRANSPORTE]) VALUES (7, CAST(0x000098AB007F2AB0 AS DateTime), CAST(47.6366310 AS Decimal(10, 7)), CAST(-122.2145580 AS Decimal(10, 7)), N'8BA21D90-3F90-407F-BAAE-800B04B1F5ED', 0, 0, CAST(0.0 AS Decimal(10, 1)), CAST(0x000098AB007F2AB0 AS DateTime), N'na', 137, N'na', N'gpsTracker', NULL)
INSERT [dbo].[GPS_LOCATION] ([ID_GPS_LOCATION], [LAST_UPDATE], [LATITUDE], [LONGITUDE], [SESSION_ID], [SPEED], [DIRECTION], [DISTANCE], [GPS_TIME], [LOCATION_METHOD], [ACCURACY], [EXTRA_INFO], [EVENT_TYPE], [ID_TRANSPORTE]) VALUES (8, CAST(0x000098AB007F7100 AS DateTime), CAST(47.6379610 AS Decimal(10, 7)), CAST(-122.2017690 AS Decimal(10, 7)), N'8BA21D90-3F90-407F-BAAE-800B04B1F5ED', 0, 0, CAST(0.0 AS Decimal(10, 1)), CAST(0x000098AB007F7100 AS DateTime), N'na', 137, N'na', N'gpsTracker', NULL)
INSERT [dbo].[GPS_LOCATION] ([ID_GPS_LOCATION], [LAST_UPDATE], [LATITUDE], [LONGITUDE], [SESSION_ID], [SPEED], [DIRECTION], [DISTANCE], [GPS_TIME], [LOCATION_METHOD], [ACCURACY], [EXTRA_INFO], [EVENT_TYPE], [ID_TRANSPORTE]) VALUES (9, CAST(0x000098AB007FB750 AS DateTime), CAST(47.6429350 AS Decimal(10, 7)), CAST(-122.2095790 AS Decimal(10, 7)), N'8BA21D90-3F90-407F-BAAE-800B04B1F5ED', 0, 0, CAST(0.0 AS Decimal(10, 1)), CAST(0x000098AB007FB750 AS DateTime), N'na', 137, N'na', N'gpsTracker', NULL)
/****** Object:  Table [dbo].[ALUMNO]    Script Date: 07/20/2015 16:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ALUMNO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ALUMNO](
	[ID_ALUMNO] [int] NOT NULL,
	[ID_ESCUELA] [int] NULL,
	[ID_TRANSPORTE] [int] NULL,
	[ID_RESPONSABLE_ALUMNO] [int] NULL,
	[ID_INFORMACION_ALUMNO] [int] NULL,
	[ID_INFORMACION_NOTIFICACION] [int] NULL,
	[ID_DIRECCION_RECOGE] [int] NULL,
	[ID_INFORMACION_ENREGA] [nchar](10) NULL,
 CONSTRAINT [PK_ALUMNO] PRIMARY KEY CLUSTERED 
(
	[ID_ALUMNO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[BITACORA_EVENTO]    Script Date: 07/20/2015 16:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BITACORA_EVENTO](
	[ID_BITACORA_EVENTO] [int] NOT NULL,
	[ID_TRANSPORTE] [int] NULL,
	[ID_ALUMNO] [int] NULL,
	[FECHA_EVENTO] [datetime] NULL,
	[ID_DETALLE_EVENTO] [int] NULL,
 CONSTRAINT [PK_BITACORA_EVENTO] PRIMARY KEY CLUSTERED 
(
	[ID_BITACORA_EVENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[ALUMNO_X_USUARIO]    Script Date: 07/20/2015 16:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ALUMNO_X_USUARIO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ALUMNO_X_USUARIO](
	[ID_ALUMNO] [int] NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[FECHA_ALTA] [date] NOT NULL,
	[ID_ALUMNO_X_USUARIO] [int] NOT NULL,
 CONSTRAINT [PK_ALUMNO_X_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_ALUMNO_X_USUARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  ForeignKey [FK_ALUMNO_ESCUELA]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO]  WITH CHECK ADD  CONSTRAINT [FK_ALUMNO_ESCUELA] FOREIGN KEY([ID_ESCUELA])
REFERENCES [dbo].[ESCUELA] ([ID_ESCUELA])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] CHECK CONSTRAINT [FK_ALUMNO_ESCUELA]
GO
/****** Object:  ForeignKey [FK_ALUMNO_INFORMACION_ALUMNO]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_INFORMACION_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO]  WITH CHECK ADD  CONSTRAINT [FK_ALUMNO_INFORMACION_ALUMNO] FOREIGN KEY([ID_INFORMACION_ALUMNO])
REFERENCES [dbo].[INFORMACION_ALUMNO] ([ID_INFORMACION_ALUMNO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_INFORMACION_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] CHECK CONSTRAINT [FK_ALUMNO_INFORMACION_ALUMNO]
GO
/****** Object:  ForeignKey [FK_ALUMNO_INFORMACION_NOTIFICACION]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_INFORMACION_NOTIFICACION]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO]  WITH CHECK ADD  CONSTRAINT [FK_ALUMNO_INFORMACION_NOTIFICACION] FOREIGN KEY([ID_INFORMACION_NOTIFICACION])
REFERENCES [dbo].[INFORMACION_NOTIFICACION] ([ID_INFORMACION_NOTIFICACION])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_INFORMACION_NOTIFICACION]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] CHECK CONSTRAINT [FK_ALUMNO_INFORMACION_NOTIFICACION]
GO
/****** Object:  ForeignKey [FK_ALUMNO_RESPONSABLE_ALUMNO]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_RESPONSABLE_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO]  WITH CHECK ADD  CONSTRAINT [FK_ALUMNO_RESPONSABLE_ALUMNO] FOREIGN KEY([ID_RESPONSABLE_ALUMNO])
REFERENCES [dbo].[RESPONSABLE_ALUMNO] ([ID_RESPONSABLE_ALUMNO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_RESPONSABLE_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] CHECK CONSTRAINT [FK_ALUMNO_RESPONSABLE_ALUMNO]
GO
/****** Object:  ForeignKey [FK_ALUMNO_TRANSPORTE]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO]  WITH CHECK ADD  CONSTRAINT [FK_ALUMNO_TRANSPORTE] FOREIGN KEY([ID_TRANSPORTE])
REFERENCES [dbo].[TRANSPORTE] ([ID_TRANSPORTE])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO]'))
ALTER TABLE [dbo].[ALUMNO] CHECK CONSTRAINT [FK_ALUMNO_TRANSPORTE]
GO
/****** Object:  ForeignKey [FK_ALUMNO_X_USUARIO_ALUMNO]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_X_USUARIO_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO_X_USUARIO]'))
ALTER TABLE [dbo].[ALUMNO_X_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_ALUMNO_X_USUARIO_ALUMNO] FOREIGN KEY([ID_ALUMNO])
REFERENCES [dbo].[ALUMNO] ([ID_ALUMNO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_X_USUARIO_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO_X_USUARIO]'))
ALTER TABLE [dbo].[ALUMNO_X_USUARIO] CHECK CONSTRAINT [FK_ALUMNO_X_USUARIO_ALUMNO]
GO
/****** Object:  ForeignKey [FK_ALUMNO_X_USUARIO_USUARIO]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_X_USUARIO_USUARIO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO_X_USUARIO]'))
ALTER TABLE [dbo].[ALUMNO_X_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_ALUMNO_X_USUARIO_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ALUMNO_X_USUARIO_USUARIO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ALUMNO_X_USUARIO]'))
ALTER TABLE [dbo].[ALUMNO_X_USUARIO] CHECK CONSTRAINT [FK_ALUMNO_X_USUARIO_USUARIO]
GO
/****** Object:  ForeignKey [FK_BITACORA_EVENTO_ALUMNO]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO]  WITH CHECK ADD  CONSTRAINT [FK_BITACORA_EVENTO_ALUMNO] FOREIGN KEY([ID_ALUMNO])
REFERENCES [dbo].[ALUMNO] ([ID_ALUMNO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_ALUMNO]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO] CHECK CONSTRAINT [FK_BITACORA_EVENTO_ALUMNO]
GO
/****** Object:  ForeignKey [FK_BITACORA_EVENTO_DETALLE_EVENTO]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_DETALLE_EVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO]  WITH CHECK ADD  CONSTRAINT [FK_BITACORA_EVENTO_DETALLE_EVENTO] FOREIGN KEY([ID_DETALLE_EVENTO])
REFERENCES [dbo].[DETALLE_EVENTO] ([ID_DETALLE_EVENTO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_DETALLE_EVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO] CHECK CONSTRAINT [FK_BITACORA_EVENTO_DETALLE_EVENTO]
GO
/****** Object:  ForeignKey [FK_BITACORA_EVENTO_TRANSPORTE]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO]  WITH CHECK ADD  CONSTRAINT [FK_BITACORA_EVENTO_TRANSPORTE] FOREIGN KEY([ID_TRANSPORTE])
REFERENCES [dbo].[TRANSPORTE] ([ID_TRANSPORTE])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BITACORA_EVENTO_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[BITACORA_EVENTO]'))
ALTER TABLE [dbo].[BITACORA_EVENTO] CHECK CONSTRAINT [FK_BITACORA_EVENTO_TRANSPORTE]
GO
/****** Object:  ForeignKey [FK_CHOFER_INFORMACION_CONTACTO]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CHOFER_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CHOFER]'))
ALTER TABLE [dbo].[CHOFER]  WITH CHECK ADD  CONSTRAINT [FK_CHOFER_INFORMACION_CONTACTO] FOREIGN KEY([ID_INFORMACION_CONTACTO])
REFERENCES [dbo].[INFORMACION_CONTACTO] ([ID_INFORMACION_CONTACTO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CHOFER_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CHOFER]'))
ALTER TABLE [dbo].[CHOFER] CHECK CONSTRAINT [FK_CHOFER_INFORMACION_CONTACTO]
GO
/****** Object:  ForeignKey [FK_DETALLE_EVENTO_TIPO_EVENTO]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DETALLE_EVENTO_TIPO_EVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[DETALLE_EVENTO]'))
ALTER TABLE [dbo].[DETALLE_EVENTO]  WITH CHECK ADD  CONSTRAINT [FK_DETALLE_EVENTO_TIPO_EVENTO] FOREIGN KEY([ID_TIPO_EVENTO])
REFERENCES [dbo].[TIPO_EVENTO] ([ID_TIPO_EVENTO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DETALLE_EVENTO_TIPO_EVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[DETALLE_EVENTO]'))
ALTER TABLE [dbo].[DETALLE_EVENTO] CHECK CONSTRAINT [FK_DETALLE_EVENTO_TIPO_EVENTO]
GO
/****** Object:  ForeignKey [FK_ESCUELA_ESCUELA_X_ADMINISTRADOR]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ESCUELA_ESCUELA_X_ADMINISTRADOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[ESCUELA]'))
ALTER TABLE [dbo].[ESCUELA]  WITH CHECK ADD  CONSTRAINT [FK_ESCUELA_ESCUELA_X_ADMINISTRADOR] FOREIGN KEY([ID_ESCUELA])
REFERENCES [dbo].[ESCUELA_X_ADMINISTRADOR] ([ID_ESCUELA_X_ADMINISTRADOR])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ESCUELA_ESCUELA_X_ADMINISTRADOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[ESCUELA]'))
ALTER TABLE [dbo].[ESCUELA] CHECK CONSTRAINT [FK_ESCUELA_ESCUELA_X_ADMINISTRADOR]
GO
/****** Object:  ForeignKey [FK_ESCUELA_X_ADMINISTRADOR_ADMINISTRADOR]    Script Date: 07/20/2015 16:52:06 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ESCUELA_X_ADMINISTRADOR_ADMINISTRADOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[ESCUELA_X_ADMINISTRADOR]'))
ALTER TABLE [dbo].[ESCUELA_X_ADMINISTRADOR]  WITH CHECK ADD  CONSTRAINT [FK_ESCUELA_X_ADMINISTRADOR_ADMINISTRADOR] FOREIGN KEY([ID_ADMINISTRADOR])
REFERENCES [dbo].[ADMINISTRADOR] ([ID_ADMINISTRADOR])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ESCUELA_X_ADMINISTRADOR_ADMINISTRADOR]') AND parent_object_id = OBJECT_ID(N'[dbo].[ESCUELA_X_ADMINISTRADOR]'))
ALTER TABLE [dbo].[ESCUELA_X_ADMINISTRADOR] CHECK CONSTRAINT [FK_ESCUELA_X_ADMINISTRADOR_ADMINISTRADOR]
GO
/****** Object:  ForeignKey [FK_GPS_LOCATION_TRANSPORTE]    Script Date: 07/20/2015 16:52:07 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_GPS_LOCATION_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[GPS_LOCATION]'))
ALTER TABLE [dbo].[GPS_LOCATION]  WITH CHECK ADD  CONSTRAINT [FK_GPS_LOCATION_TRANSPORTE] FOREIGN KEY([ID_TRANSPORTE])
REFERENCES [dbo].[TRANSPORTE] ([ID_TRANSPORTE])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_GPS_LOCATION_TRANSPORTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[GPS_LOCATION]'))
ALTER TABLE [dbo].[GPS_LOCATION] CHECK CONSTRAINT [FK_GPS_LOCATION_TRANSPORTE]
GO
/****** Object:  ForeignKey [FK_RESPONSABLE_ALUMNO_INFORMACION_CONTACTO]    Script Date: 07/20/2015 16:52:07 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RESPONSABLE_ALUMNO_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[RESPONSABLE_ALUMNO]'))
ALTER TABLE [dbo].[RESPONSABLE_ALUMNO]  WITH CHECK ADD  CONSTRAINT [FK_RESPONSABLE_ALUMNO_INFORMACION_CONTACTO] FOREIGN KEY([ID_INFORMACION_CONTACTO])
REFERENCES [dbo].[INFORMACION_CONTACTO] ([ID_INFORMACION_CONTACTO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RESPONSABLE_ALUMNO_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[RESPONSABLE_ALUMNO]'))
ALTER TABLE [dbo].[RESPONSABLE_ALUMNO] CHECK CONSTRAINT [FK_RESPONSABLE_ALUMNO_INFORMACION_CONTACTO]
GO
/****** Object:  ForeignKey [FK_TRANSPORTE_CHOFER]    Script Date: 07/20/2015 16:52:07 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_CHOFER]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE]  WITH CHECK ADD  CONSTRAINT [FK_TRANSPORTE_CHOFER] FOREIGN KEY([ID_CHOFER])
REFERENCES [dbo].[CHOFER] ([ID_CHOFER])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_CHOFER]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE] CHECK CONSTRAINT [FK_TRANSPORTE_CHOFER]
GO
/****** Object:  ForeignKey [FK_TRANSPORTE_ESCUELA]    Script Date: 07/20/2015 16:52:07 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE]  WITH CHECK ADD  CONSTRAINT [FK_TRANSPORTE_ESCUELA] FOREIGN KEY([ID_ESCUELA])
REFERENCES [dbo].[ESCUELA] ([ID_ESCUELA])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE] CHECK CONSTRAINT [FK_TRANSPORTE_ESCUELA]
GO
/****** Object:  ForeignKey [FK_TRANSPORTE_INFORMACION_UNIDAD]    Script Date: 07/20/2015 16:52:07 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_INFORMACION_UNIDAD]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE]  WITH CHECK ADD  CONSTRAINT [FK_TRANSPORTE_INFORMACION_UNIDAD] FOREIGN KEY([ID_INFORMACION_UNIDAD])
REFERENCES [dbo].[INFORMACION_UNIDAD] ([ID_INFORMACION_UNIDAD])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TRANSPORTE_INFORMACION_UNIDAD]') AND parent_object_id = OBJECT_ID(N'[dbo].[TRANSPORTE]'))
ALTER TABLE [dbo].[TRANSPORTE] CHECK CONSTRAINT [FK_TRANSPORTE_INFORMACION_UNIDAD]
GO
/****** Object:  ForeignKey [FK_USUARIO_INFORMACION_CONTACTO]    Script Date: 07/20/2015 16:52:07 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO]'))
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_INFORMACION_CONTACTO] FOREIGN KEY([ID_INFORMACION_CONTACTO])
REFERENCES [dbo].[INFORMACION_CONTACTO] ([ID_INFORMACION_CONTACTO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_INFORMACION_CONTACTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO]'))
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USUARIO_INFORMACION_CONTACTO]
GO
/****** Object:  ForeignKey [FK_USUARIO_X_ESCUELA_ESCUELA]    Script Date: 07/20/2015 16:52:07 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_X_ESCUELA_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO_X_ESCUELA]'))
ALTER TABLE [dbo].[USUARIO_X_ESCUELA]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_X_ESCUELA_ESCUELA] FOREIGN KEY([ID_ESCUELA])
REFERENCES [dbo].[ESCUELA] ([ID_ESCUELA])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_X_ESCUELA_ESCUELA]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO_X_ESCUELA]'))
ALTER TABLE [dbo].[USUARIO_X_ESCUELA] CHECK CONSTRAINT [FK_USUARIO_X_ESCUELA_ESCUELA]
GO
/****** Object:  ForeignKey [FK_USUARIO_X_ESCUELA_USUARIO]    Script Date: 07/20/2015 16:52:07 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_X_ESCUELA_USUARIO]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO_X_ESCUELA]'))
ALTER TABLE [dbo].[USUARIO_X_ESCUELA]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_X_ESCUELA_USUARIO] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_USUARIO_X_ESCUELA_USUARIO]') AND parent_object_id = OBJECT_ID(N'[dbo].[USUARIO_X_ESCUELA]'))
ALTER TABLE [dbo].[USUARIO_X_ESCUELA] CHECK CONSTRAINT [FK_USUARIO_X_ESCUELA_USUARIO]
GO
